# -- Site Configuration --
# Refer to the theme docs for more details index.md.md each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
baseURL = "https://mohamedabouzid.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[permalinks]
blogs = "/blog/:year/:month/:day/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
