languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Mohamed Abouzid"
copyright = "© 2025 Mohamed Abouzid"

[params]
  dateFormat = "2 January 2006"

  description = "Personal website of Mohamed Abouzid"

[params.author]
  name = "Mohamed Abouzid"
  image = "img/avatar.png"
  headline = "Bioinformatician, Data Scientist & Content Creator"
  bio = "Bioinformatician, Data Scientist & Content Creator."
  links = [
    { youtube = "https://youtube.com/" },
    { instagram = "https://www.instagram.com/_mohamed.at.abouzid/" },
    { github = "https://github.com/MohamedAbouzid1" },
    { linkedin = "https://www.linkedin.com/in/mohamed-abouzid/" },
  ]